server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: ${PRODUCT_DB_URL:jdbc:mysql://localhost:3306/product_db?createDatabaseIfNotExist=true}
    username: ${PRODUCT_DB_USERNAME:root}
    password: ${PRODUCT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000
            loggerLevel: basic

jwt:
  public-key: ${JWT_PUBLIC_KEY}

logging:
  file:
    name: ${LOG_ROOT:../logs}/product-service.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_ROOT:../logs}/product-service.%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 10MB
      max-history: 14
      total-size-cap: 1GB
